plugins {
    id 'java'
    id("xyz.jpenilla.run-paper") version "2.3.1"
    id("com.gradleup.shadow") version "9.3.1"
}

group = 'com.mlc'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "placeholderapi"
        url = 'https://repo.extendedclip.com/releases/'
    }
    maven { url = "https://repo.codemc.io/repository/maven-releases/" }
    maven { url = "https://repo.codemc.io/repository/maven-snapshots/" }
    //ce
    maven { url 'https://repo.momirealms.net/releases/' }
    //fasw
    maven { url = "https://repo.papermc.io/repository/maven-public/" }
    maven { url = "https://maven.enginehub.org/repo/" }
}

dependencies {
    compileOnly("com.github.retrooper:packetevents-spigot:2.13.0")
    compileOnly("io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT")
    compileOnly 'me.clip:placeholderapi:2.11.7'
    implementation 'net.kyori:adventure-text-minimessage:4.13.0'
    //ce
    compileOnly 'net.momirealms:craft-engine-core:26.8.2' // 将 "{version}" 替换为插件稳定版本
    compileOnly 'net.momirealms:craft-engine-bukkit:26.8.2' // 例如 0.0.60
    //fasw
    compileOnly(platform("com.intellectualsites.bom:bom-newest:1.56"))
    compileOnly("com.fastasyncworldedit:FastAsyncWorldEdit-Core")
    compileOnly("com.fastasyncworldedit:FastAsyncWorldEdit-Bukkit") {
        transitive = false
    }
}


tasks.shadowJar {
    relocate("com.github.retrooper", "com.mlc.mlcgames.libs.packetevents")
    relocate("io.github.retrooper", "com.mlc.mlcgames.libs.packetevents")
//    relocate("net.kyori", "com.mlc.mlcgames.libs.kyori")
    relocate("com.google.gson", "com.mlc.mlcgames.libs.gson")
}

def targetJavaVersion = 21
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}
