lobby: ''

bankgame:
  tvtgametime: 10
  tvpgametime: 10
  bankgameLocation: ''
  pliceteamLocation: ''
  theifteamLocation: ''
  spectatelocation: ''
  powerLocation1: ''
  powerLocation2: ''
  leaveLocation1: ''
  leaveLocation2: ''



