scoreboard:

lobby: ''

bankgame:
  requirescore: 2000
  breaklocktime: 10
  lightbreaktime: 10
  lightfixtime: 20

  tvtgametime: 400
  tvpgametime: 400
  bankgameLocation: ''
  pliceteamLocation: ''
  theifteamLocation: ''
  spectatelocation: ''
  lobbyLocation: ''
  powerLocation1: ''
  powerLocation2: ''
  leaveLocation1: ''
  leaveLocation2: ''
  cornerLocation1: ''
  cornerLocation2: ''
  thiefteamLocation1: ''
  thiefteamLocation2: ''


