name: mlcgames
version: '1.0-SNAPSHOT'
main: com.mlc.mlcgames.Mlcgames
api-version: '1.21'
authors: [ Mr_bl ]
commands:
  reload:
    description: 重载
  bankgameprepare:
    description: 准备
  bankgamereload:
    description: 重载
  bankgameend:
    description: 结束
  zombieday:
    description: 僵尸末日
